### PR TITLE
Fixes

### LINKED ISSUE #10: Problem loading from source
Trying to modify, but when I git clone the master branch and symlink into Atom, I get a problem with the `stata.cson` file: 

    /Users/Nick/.atom/packages/language-stata/grammars/stata.cson: unmatched OUTDENT in /Users/Nick/.atom/packages/language-stata/grammars/stata.cson
    Hide Stack Trace
    [stdin]:31:8: error: unmatched OUTDENT
          {
           ^
      at /Users/Nick/.atom/packages/language-stata/grammars/stata.cson:1:1

Is this a clone issue or problem with master branch?

(also, this repo seems super dead. Is it still active? @puterleat @rhoconlinux ?)

### PR DESCRIPTION
**Pull request by nickeubank**
Closes #10 and partially addresses #11. 

Mostly reverts commit 4aeb65ed4a7740f88fa4fddecc8bc420fc383fc, which appears to have corrupted the stata.cson file.

### CODE REVIEW

**Comment by puterleat** [comment]
Nick... thanks for this. I've mostly switched to R now and am not working on this any more. Are you interested in taking over the repo. You might also be interested in https://github.com/benwhalley/statpipe which would be one way of making Stata code runnable and presentable within atom.

**Comment by nickeubank** [comment]
@puterleat sure, if you don't mind also pointing me to directions on pushing to the atom repository. I mostly work in python now (some R), but I have a soft spot for stata. :)

**Comment by nickeubank** [comment]
@benwhalley Thanks! Last question: how do I ship?

**Comment by benwhalley** [comment]
The docs are here… http://flight-manual.atom.io
you need the apm command line tool. I think you should have access to push a revision now that you’re a collaborator on the repo.

**Comment by nickeubank** [comment]
Great, thanks! :)

**Pull request merged**
